sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
- '7'
before_script:
- npm install standard
script:
- npm install istanbul
- istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- test
- standard
after_script:
- npm install coveralls
- cat ./coverage/lcov.info | coveralls
